#! /bin/bash
# /etc/init.d/userdata
#

### BEGIN INIT INFO
# Provides:          userdata
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Apply userdata to /etc/hosts
# Description:       Apply userdata to /etc/hosts
### END INIT INFO

USERDATA_SCRIPT="/home/xlt/apply-userdata.sh"
USERDATA_BEGIN_FLAG="# User data entries START"
USERDATA_END_FLAG="# User data entries END"
HOSTS_FILE="/etc/hosts"

# put the getUserData.sh into an reachable place, this happens in userdata and xlt
# since it depends on the runlevel which is execudet first
cp ~/xlt-home/getUserData.sh /var/local/


function cleanup {
	SED="sed -i '/$USERDATA_BEGIN_FLAG/,/$USERDATA_END_FLAG/ { d }' $HOSTS_FILE"
	eval $SED
}

# Carry out specific functions when asked to by the system
case "$1" in
	start)
		echo "Retrieving UserData"
		NEW_HOSTS=$(/var/local/getUserData.sh hosts)

		echo "Remove old user data"
		cleanup


		echo "Apply user data"
		sudo echo "$USERDATA_BEGIN_FLAG" >> $HOSTS_FILE
		sudo echo -E "$NEW_HOSTS" >> $HOSTS_FILE
		sudo echo "$USERDATA_END_FLAG" >> $HOSTS_FILE
		;;
	stop)
		cleanup
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 0
		;;
esac

exit 0
